In [1]:
# 파이토치 프레임 워크 불러오는 부분
import torch 
import torchvision # image processing에 특화된 라이브러리
import torch.nn as nn
import torchvision.transforms as transforms # Data Augmentation에 특화된 라이브러리
import numpy as np

In [2]:
X = torch.Tensor(2,3) #2행 3열의 텐서를 하나 생성
X.shape
X.size()

X = torch.Tensor([[1,2,3],[4,5,6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
'''
tensor() 인자값으로 
data : 값 지정, 초기화
dtype
requires_grad에 대해서 미분 적용할지 여부
'''
x = torch.tensor(data=[2.0,3.0], requires_grad=True)
x

y = x**2
y

pred = 2*y+3 # 11,21

target = torch.tensor([3.0,4.0]) #3, 4
target

tensor([3., 4.])

In [4]:
'''
위에 나온 결과를 바탕으로 
경사하강법을 이용해서
미분을 사용해서 Loss에 대한 책임을 묻겠다.
기울기가 계산이 될 것이다.(미분 계산)
--> BackPropagation을 적용하려면 backward() 함수를 호출
Loss를 줄여나가 보겠다.
'''

'\n위에 나온 결과를 바탕으로 \n경사하강법을 이용해서\n미분을 사용해서 Loss에 대한 책임을 묻겠다.\n기울기가 계산이 될 것이다.(미분 계산)\n--> BackPropagation을 적용하려면 backward() 함수를 호출\nLoss를 줄여나가 보겠다.\n'

In [5]:
loss = torch.sum(torch.abs(pred - target))
print('Loss',loss)

Loss tensor(25., grad_fn=<SumBackward0>)


In [6]:
loss.backward()

In [7]:
print(x.grad, pred.grad)

tensor([ 8., 12.]) None


<ipython-input-7-f0672e5ef792>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(x.grad, pred.grad)


## Create Tens....Using NeuralNet

In [8]:
x = torch.randn(10,3)
y = torch.randn(10,2)
print(x)
print(y)

tensor([[ 0.4353,  0.6515,  0.1465],
        [-0.1266, -1.3723, -0.7454],
        [-0.5641, -0.2480, -0.3307],
        [ 0.4668,  0.2616,  0.1623],
        [-0.6891, -0.0710,  0.1789],
        [-2.1267,  0.6610,  0.2195],
        [-1.2965,  1.9744,  1.2464],
        [-0.6071, -0.0032,  0.1651],
        [-0.4434,  0.0761, -1.7083],
        [-0.9013, -0.0233, -0.9140]])
tensor([[-0.4619, -0.1061],
        [ 1.5990,  0.3641],
        [-1.1861,  0.0230],
        [-1.2324,  0.9560],
        [-0.6554, -0.1082],
        [-0.1205, -1.1527],
        [-0.2543, -0.4357],
        [-1.7944,  0.9793],
        [-0.1302,  0.0150],
        [ 1.1660, -1.6269]])


In [9]:
linear = nn.Linear(3,2)
print('w', linear.weight)
print('b', linear.bias)

w Parameter containing:
tensor([[-0.3275,  0.5110, -0.1635],
        [ 0.2884,  0.0657, -0.1736]], requires_grad=True)
b Parameter containing:
tensor([-0.3761, -0.3629], requires_grad=True)


In [11]:
# 객체출력, parameters() 함수는 모델안의 학습의 주체인 w, b를 내포하고 있는 객체
# parameters() 함수는 w, b를 해킹한 함수이다.
print(linear.parameters())

# Loss function을 미리 선정의 해두었다.
loss_function = nn.MSELoss()

# optimizer(하산하는 방법)를 미리 정의
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# 위에서 만든 모델에서 값을 입력..결과로 예측값이 나온다.
pred = linear(x)

# 정답과 예측값을 이용해서 위에서 선정의한 Loss를 계산..L(W)
loss = loss_function(pred, y)
print('loss before step BackPropagation',loss.item())

<generator object Module.parameters at 0x000001BED5DF26D0>
loss before step BackPropagation 1.0043259859085083


In [18]:
'''
loss값이 나왔다는 것은
모델의 예측값에 대한 잘잘못을 정량화 했다는 것이다.

이 값을 바탕으로 BackPropagation을 하면 w, b에 대한 미분값
즉 얼마만큼 보정해야 하는지의 값이 나온다.
그 값을 이용해서 다시 하강(기울기 수정)하기 때문에
2번째에는 Loss가 줄어들어야 한다.
'''
loss.backward() # loss값에 대한 w의 책임을 묻는다.....미분을 적용
print('dL/dw', linear.weight.grad)
print('dL/db', linear.bias.grad)

dL/dw tensor([[-0.6124,  1.2488,  0.8481],
        [ 0.0388,  0.0180, -0.2004]])
dL/db tensor([ 0.4869, -0.7613])


In [19]:
optimizer.step() #위에서 수정된 값으로 하강을 진행한다...학습을 한다.

#반복 효과
pred = linear(x)
loss = loss_function(pred,y)

print('loss after BackPropagation : ', loss.item())


loss after BackPropagation :  0.9782593846321106
